server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://172.172.172.249:3306/ikang_data?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
    username: op2c
    password: op2c!@#
  # ===== Redis 配置 =====
  redis:
    database: 3
    # Redis服务器地址
    #    host: 172.172.172.197
    #    host: 172.172.172.197
    # Redis服务器连接端口
    #    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 120000
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
    sentinel:
      master: redis-ha1
      nodes: 172.172.172.147:26379,172.172.172.148:26379

logging:
  level:
    com.ikang.idata.api.DictService: debug
    com.ikang.idata.api.TelephoneService: debug
    com.ikang.idata.api.BSidePushRecordsService: debug
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml