server:
  port: 90
spring:
  application:
    name: cloud-consumer-feign-order80
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka

#设置Feign客户端超时时间（openfeign默认支持ribbon）
ribbon:
  #查询超时时间，超时就访问其他实例
  ReadTimeout:  3000
  #连接超时时间，超时就访问其他实例
  ConnectTimeout: 3000
  MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 1 #重试负载均衡访问其他的实例最大重试次数,不包括首次调用
  OkToRetryOnAllOperations: false #非Get请求是否重试，容易重复添加

#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 9000

#开启OpenFeign日志打印功能
logging:
  level:
    com.atguigu.springcloud.service.PaymentFeignService: debug


